apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cloud-devops-cluster
  region: ap-south-1
  version: "1.33"

vpc:
  nat:
    gateway: Disable

managedNodeGroups:
  - name: cloud-devops-nodes
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    volumeSize: 20
    privateNetworking: false