name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  IMAGE_NAME: ghcr.io/yuvi1-1/cloud-devops-platform
  AWS_REGION: ap-south-1
  EKS_CLUSTER: cloud-devops-cluster

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            ref: ${{ github.event.workflow_run.head_sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::403659231418:role/GitHubActions-CloudDevOps
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: Verify EKS cluster
        run: |
          aws eks describe-cluster \
            --region $AWS_REGION \
            --name $EKS_CLUSTER \
            --query 'cluster.status' \
            --output text

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name $EKS_CLUSTER

      - name: Deploy with Helm
        run: |
          helm upgrade --install cloud-devops helm/cloud-devops \
            --set image.repository=$IMAGE_NAME \
            --set image.tag=${{ github.event.workflow_run.head_sha }}

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/cloud-devops-app --timeout=180s

      - name: Verify deployment
        run: |
          kubectl get deployment cloud-devops-app
          kubectl get pods -l app=cloud-devops-app